=== nitinkc/SpringMVCTraining/src/main/webapp/xsd/fruits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.soap.com/fruits"
	xmlns:tns="http://www.soap.com/fruits" elementFormDefault="qualified">
	
	<!-- global elements -->
	<element name="fruits"   type="tns:ffruits"/>
	
	<complexType name="ffruits">
	    <sequence>
	    	<element name="fruit"  type="tns:dfruit"  minOccurs="1" maxOccurs="unbounded"/>
	    </sequence>
	</complexType>
	
	<complexType name="dfruit">
	      <sequence>
				       <element name="fid" type="int" minOccurs="1" maxOccurs="1"/>
	      				<element name="name" type="string" minOccurs="1" maxOccurs="1"/>
	      				<element name="color" type="string" minOccurs="1" maxOccurs="1"/>
	      				<element name="taste" type="string" minOccurs="1" maxOccurs="1"/>
	      				<element name="price" type="int" minOccurs="1" maxOccurs="1"/>
	      				<element name="pcity" type="string" minOccurs="1" maxOccurs="1"/>
	      				<element name="quantity" type="int" minOccurs="1" maxOccurs="1"/>
	      				<element name="image" type="base64Binary" minOccurs="0" maxOccurs="1"/>
	      </sequence>
	</complexType>
	
</schema>

=== nitinkc/SpringMVCTraining/src/main/webapp/xsd/fruits1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:fruits xmlns:tns="http://www.soap.com/fruits"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.soap.com/fruits fruits.xsd ">
  <tns:fruit>
    <tns:fid>0</tns:fid>
    <tns:name>tns:name</tns:name>
    <tns:color>tns:color</tns:color>
    <tns:taste>tns:taste</tns:taste>
    <tns:price>0</tns:price>
    <tns:pcity>tns:pcity</tns:pcity>
    <tns:quantity>0</tns:quantity>
  </tns:fruit>
</tns:fruits>

=== nitinkc/SpringMVCTraining/src/main/webapp/xsd/fruits.xml
<?xml version="1.0" encoding="UTF-8"?>
<fruits  xmlns="http://www.soap.com/fruits"   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.soap.com/fruits fruits.xsd">
        <fruit>
                <fid>828</fid>
                <name>Papaya</name>
                <color>Papaya</color>
                <taste>Sweet</taste>
                <price>143</price>
                <pcity>Papaya</pcity>
                <quantity>100</quantity>
          </fruit>
            <fruit>
                <fid>828</fid>
                <name>Papaya</name>
                <color>Papaya</color>
                <taste>Sweet</taste>
                <price>143</price>
                <pcity>Papaya</pcity>
                <quantity>20</quantity>
       </fruit>
</fruits>
